[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[test]
coverage = true
coverageThreshold = { lines = 1.0 }
silent = true
coveragePathIgnorePatterns = [
  "src/utils/**",
  "*.config.js",
  "./build.ts",
  "./bun-env.d.ts",
  "src/admin/**",
  "*.test.ts",
  "tests/**",
]